name: Menu Server CI
on:
  - push
# tag::pr[]
  - pull_request
# end::pr[]
jobs:
  menu_server:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup JDK Zulu 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Setup Maven 3.9.0
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.0
      - name: Check Maven tooling
        run: mvn -v
      - name: Build application
        run: mvn compile
      - name: Package application
        run: mvn package
