name: Vehicle Server CI
on:
  - push
# tag::pr[]
  - pull_request
# end::pr[]
jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Go
      - uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
      - name: Check Go Version
        run: go version
      # tag::ci[]
      - name: Run Unit Tests
        run: make unit_test
      - name: Run Integration Tests
        run: make integration_test
      # end::ci[]
      - name: Build application
        run: make build
      # tag::package[]
      - name: Package Application
        run: make package
      # end::package[]
      - name: List dist output
        run: ls dist/
