[{invert}]
= Présentation de votre projet

== Contexte (1/2)

* Dans un effort d'optimisation de ses processus métiers, la cantina de Mos-Estafette s'est lancée dans un grand projet de digitalisation de la gestion de sa carte

* Le projet est divisé en deux lots:
** Une partie serveur qui stocke et expose la données de la carte via une API REST
** Une partie client qui permet de consulter et de gérer les menus de la cantina via l'API du serveur

== Contexte (2/2)

* Après une longue et épique bataille de chefs de projets et autres décideurs fonctionnels, la société **Bananes Services d'Entreprises**, spécialiste national des technologies du minitel, à remporté le lot de la partie serveur...
* ...Cependant, suite à d'un **grave accident de brainstorming** entre les 18 chefs de projet travaillant sur le dit projet et 6 mois de retard sur la première livraison, l'entreprise *Bananes* s'est retrouvée dans l'incapacité de mener le projet à son terme
* Désemparés face à cette terrible nouvelle, le conseil d'administration de la cantina à décidé de se tourner vers l'ENSG pour tenter de sauver leur transition numérique

== Prise en Main du Projet (1/2)

* Une équipe technique de **Bananes** avait commencé l'implémentation du serveur, et à fourni une archive link:media/menu-server.tar.gz[téléchargeable ICI], contenant le code source du projet
* **Bananes** vous assure qu'ils ont suivi toutes les "best practices" du développement logiciel sur minitel
** Il y à un `LISEZMOI.txt` à la racine du projet :tada:
** ... et pas grand chose d'autre?

== Prise en Main du Projet (2/2)

[source,bash]
--
# Création du répertoire menu-server
mkdir -p /workspace/menu-server && cd /workspace/menu-server

# Téléchargez le projet sur votre environnement de développement
curl -sSLO https://cicd-lectures.github.io/slides/2023/media/menu-server.tar.gz

# Décompresser et extraire l'archive téléchargée
tar xvzf ./menu-server.tar.gz
--

A partir de la vous pouvez ouvrir le fichier `LISEZMOI.txt` et commencer à suivre ses instructions.

== Comment accéder à un serveur démarré dans un Gitpod ?

* Vous avez probablement démarré un serveur web qui écoute sur  le port 8080
* Si vous souhaitez accéder par `curl` depuis terminal de votre gitpod, rien à faire
* Si vous souhaitez y accéder depuis l'extérieur de votre gitpod il vous faut une URL publique:
** `gp url 8080` vous indique l'URL du port 8080 de votre instance gitpod!
** `gp preview "$(gp url 8080)"` ouvrir votre navigateur.

[{invert}]
== Qu'est-ce qui va / ne va pas dans ce projet d'après vous?

== Triste Rencontre avec la Réalité

- Pas de gestion de version...
- Le projet ne fonctionne pas, tous les menus retournés s'appellent "TODO" :sob:
- Le correctif ne semble pas compliqué à faire...
- ... sauf que vous ne pouvez pas compiler le projet!

Il va falloir remédier à ça d'une façon ou d'une autre, sinon vous n'allez pas aller bien loin!

== 🎓 Exercice : Initialisez un dépôt git

* Nettoyez le contenu superflu du projet et initialisez un dépôt git dans le répertoire, puis créez un premier commit

* Par contenu superflu, nous entendons:
** Tout ce qui est potentiellement généré
** Les scripts de lancement obsolètes et inutiles
** Un petit renommage du LISEZMOI.txt en README.md et un coup de nettoyage de son contenu

* 💡 Pour chaque "popup" de l'éditeur (en bas à droite), choisissez "Oui" ou "Reload"

== ✅ Solution Exercice

[source,bash]
--
# On évacue le contenu inutile
rm -rf dist/ menu-server.tar.gz
rm executer.sh
# On renomme LISEZMOI.txt en README.md
mv LISEZMOI.txt README.md
# On nettoie son contenu
code README.md

# On initialise un nouveau dépôt git
git init

# On ajoute tous les fichiers contenus a la zone de staging.
git add .

# On crée un nouveau commit
git commit -m "Add initial menu-server project files"
--

== Checkpoint 🎯

* Vous avez récupéré un projet Java qui semble fonctionner...
** ..mais pas vraiment à l'état de l'art.

* Application du chapitre précédent : vous avez initialisé un projet `git` local
