
[{invert}]
= Projet 2.0

== Enoncé

* Votre prédécesseur•se a écrit une application pour le site web de la Cantina,
mais a soudainement démissionné pour partir élever des serpents sur Dagobah.

* Cette application gère la banque de menus de la cantina. On peut créer et récupérer les dits menus. Un menu est composé de plats (Dishes).
* En arrivant à la Cantina, le patron vous a envoyé un lien vers une archive contenant
le code source Java d'une application Spring Boot, plus ou moins bien instrumentée...

* Votre mission : Faire en sorte d'industrialiser cette application avec les connaissances acquises durant ce cours.

== Récupérer l'application

* Vous pouvez récupérer link:media/project-2.0-src.tar.gz[ici l'archive Tar-gzippé nommée `project-2.0-src.tar.gz`,target="_blank"].
* Empreinte SHA256 : `0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5`.

== Un peu plus de détails: VCS

* Versionner et héberger le projet dans un dépôt public GitHub ou GitLab
* Possède une organisation de branches *représentant le cycle de vie de l'application*.
** Deux branches: `main` et `development`
** `main` ne devrait avoir que des **commits de merge**  (Via PR ou non ?) issus de development.
** Chaque commit de main est "taggé" et correspond à une release du logiciel avec une *version sémantique*.
** La branche `development` ne devrait avoir que des **commits** de merge issus de PRs.
* Un historique de commits à peu près propre :)

== Un peu plus de détails: PRs

* On vous conseille de travailler sur le projet uniquement par PRs (Pull Requests) qui feront office de documentation de votre travail
* Par exemple:
** PR-1: Mise en place du job de CI
** PR-2: Mise en place de Maven et activation de la compilation dans le job CI
** PR-3: Ajout des tests unitaires et activation dans job le CI
** PR-4: Ajout des tests d'intégration et activation dans le job CI
** PR-5: Mise en place du job de CD

== Un peu plus de détails: Tests

S'assurer que la couverture de test est "satisfaisante" pour la base de code fournie :

* Des tests unitaires et des tests d'intégrations sont déjà présents mais doivent être corrigés ou complétés
** Pas de nouveau fichier à créer
** Les tests présents sont considérés comme suffisants pour ce projet

== Un peu plus de détails: Maven

Utilisez maven pour gérer les dépendances et implémenter le cycle de vie technique de l'application :

* `compile`: compile l'application
* `package`: crée un jar(jar) exécutable avec la commande `java -jar <fichier.jar>`
* `test`: exécute les tests unitaires
* `verify`: exécute les tests d'intégration

== Un peu plus de détails: CI et CD

Ce projet devra être associé à un moteur d'intégration continue

(GitHub Actions, GitLab CI ou autre si vous êtes joueurs, la seule contrainte est que ce soit un SaaS gratuit et accessible publiquement)

== CI: Sur une branche de travail

* Compile l'application
* Joue les tests unitaires
* Joue les tests d'intégration
** Bonus si récupère les rapports de tests comme artifacts du job

== CI: Sur un push dans main

* Compile l'application
* Joue les tests unitaires et intégration

== CD: Sur tag pushé

* Compile l'application
* Joue les tests unitaires et intégration
* Fait une release GitHub avec le fichier JAR de l'appication (wink wink) attaché, dont le nom correspond a la version du tag.
** Bonus si Maven tient compte de la version tagguée ;)

== Pré-requis : Solution Projet 1.1 - Makefile

Voici une proposition de solution (ce n'est donc pas la seule solution possible !) pour le Projet 1.1 :

[source,yml]
----
include::../code-samples/projet-1.1/Makefile[]
----

== Pré-requis : Solution Projet 1.1 - Workflow

[source,yml]
----
include::../code-samples/projet-1.1/cantina.yml[]
----

== Critères d'évaluation

* Les critères d'évaluation sont détaillés sur cette page: https://docs.google.com/spreadsheets/d/1IMj7-fYH12Lb2OXJ9AfquVwo_GbntGggMY9sVZiWqFw/edit?usp=sharing["Notations ENSG 2020/2021",target="_blank"],
selon les grandes catégories suivantes :
** VCS / GitHub / GitLab : 6 points
** Tests : 5 points
** Maven : 4 points
** CI/CD : 5 points

== Consignes de rendu

* Envoi de l'email pointant vers ces consigne mises à jour le 09 janvier 2021
* *Deadline du rendu*: 5 semaines à partir du jour de livraison de l'application initiale, soit le 13 février 2021
* Vous devrez nous envoyer un mail (par binôme) avec :
** Pour chaque membre du binôme:
*** Nom et prénom
*** Email
*** Identifiant GitHub ou GitLab utilisé
** Le lien vers votre dépôt de rendu

== Rendu des notes

* Les notes seront rendues 3 semaines après la deadline, soit pour le 6 mars 2021 au plus tard
* Contestation/relecture : vous aurez ~ 1 semaine après le rendu des notes si jamais vous n'être pas d'accord ou souhaitez une clarification

== Un dernier mot

* Amusez vous !
* Ne passez pas plus de 10h dessus !
* Vous êtes la pour apprendre, pas pour vous rendre malade !
