
[{invert}]
= Tests automatisés

Faire en sorte qu'on ne casse pas tout quand on change quelque chose...

== Qu'est ce qu'un test ?

* C'est du code qui vérifie qu'un système fait ce qu'il est supposé faire.
* Ecrire des tests est un acte préventif et non curratif.

== Pourquoi faire des tests ?

* Ça sert a prouver que le logiciel se comporte comme attendu a tout moment.
* Ça permet de détecter au plus tôt les problèmes.

[.notes]
--
* Cela ne permet pas de corriger des bugs, cela limite le risque d'en introduire.
--

== Qu'est ce que l'on teste ?

* Une fonction
* Une combinaison de classes
* Un serveur applicatif et une base de données

On parle de SUT, System Under Test.

== Différents systemes, différents types de tests

* Test unitaire
* Test d'integration
* Test de bout en bout

== Test unitaire

* Test validant le bon comportement une unité de code (fonction, méthode...)
* Prouve que l'unité de code interagit correctement avec les autres unités.
* Par exemple :
** Retourne les bonnes valeur en fonction des paramètres donnés
** Appelle la bonne methode du bon attribut avec les bons paramètres

== Test Unitaire : Mise en place

* Accédez à link:https://gitpod.io#https://github.com/cicd-lectures/demoapp[l'environnement de travail]
* Passez sur la branche `ut-exercise-1` (`git checkout ut-exercise-1`) et rafraichissez l'explorateur de fichier
* Exécutez les tests unitaires avec la commande `mvn test` dans le terminal en bas

== Test Unitaire : Exercice 1

Implementez la methode `greet` de la classe `GreeterService`

* Si l'age de l'utilisateur est inferieur a 10, alors retourner "Hi"
* Si l'age de l'utilisateur est entre 10 et 20, alors retourner "Hey"
* Si l'age de l'utilisateur est supérieur a 20, alors retourner "Hello"

== La classe `GreeterService`

[source,java]
--
// src/main/java/com/cicdlectures/demoapp/user/GreeterService.java

public class GreeterService {

  public String greet(User user) {
    // TODO
  }

}
--

== La classe `User`

[source,java]
--
// src/main/java/com/cicdlectures/demoapp/user/User.java

public class User {

  private int age;

  public User(String name, int age) {
    //...
    this.age = age;
  }

  public int getAge() {
    return this.age;
  }
}
--

== La classe `GreeterServiceTests`

[source,java]
--
// src/test/java/com/cicdlectures/demoapp/user/GreeterServiceTests.java

class GreeterServiceTests {

  private GreeterService subject;

  @BeforeEach
  public void init() {
    this.subject = new GreeterService();
  }

  @Test
  void greetsUserWithAgeBelow10WithHi() {
    // ...
  }
}
--


== Un exemple de test

[source,java]
--
// src/test/java/com/cicdlectures/demoapp/user/GreeterServiceTests.java

  @Test
  @DisplayName("greets user with age below 10 with Hi")
  void greetsUserWithAgeBelow10WithHi() {
    // Instancier un nouvel utilisateur.
    User user = new User("John", 5);

    // Appeler la methode a tester.
    String got = this.subject.greet(user);

    // Verifier le résutat.
    assertEquals("Hi", got);
  }

--

== Implémentation du premier cas

[source,java]
--
// src/main/java/com/cicdlectures/demoapp/user/GreeterService.java

  public String greet(User user) {
    if (user.getAge() < 10) {
      return "Hi";
    }

    //...
  }
--


== A vous de jouer pour les deux autres cas :)

[source,java]
--
  @Test
  @DisplayName("greets user with age between 10 and 20 with Hey")
  void greetsUserWithAgeBetween10And20WithHey() {
    fail("Not implemented");
  }

  @Test
  @DisplayName("greets user above 20 with Hello")
  void greetsUserWithAgeAbove20WithHello() {
    fail("Not implemented");
  }
--

== Test Unitaire : Solution Exercice 1

[source,bash]
--
git checkout ut-exercise-1-solution
--

== Test Unitaire: Exercice 2, mise en place

[source,bash]
--
git checkout ut-exercise-2
--

== Test Unitaire : Exercice 2

Implementez la methode `createUser` de la classe `UserService` et sa suite de tests.

* Si un utilisateur avec le même nom existe déjà dans la base de données, alors on ne fait rien.
* Sinon on enregistre ce nouvel utilisateur dans la base de données.

== Base de données ?

[source,java]
--
// src/main/java/com/cicdlectures/demoapp/user/UserRepository.java

public interface UserRepository {

    // Enregistre l'utilisateur en base de donnée.
    public void saveUser(User user);

    // Retourne l'utilisateur en base qui porte le nom passé en parmètre.
    // Retourne `null` si aucun utilisateur portant le nom existe.
    public User findByName(String user);
}
--

== La classe `UserService`

[source,java]
--
// src/main/java/com/cicdlectures/demoapp/user/UserService.java

public class UserService {

  private UserRepository repo;

  public UserService(UserRepository repo) {
    this.repo = repo;
  }

  public void createUser(User user) {
    // Regarde si un utilisteur avec ce nom existe en base.

    // Sauvegarde l'utilisateur si l'utilisateur n'existe pas.
  }
}
--

== Comment tester uniquement la classe `UserService` ?

* Le `UserService` à besoin d'un `UserRepository` pour fonctionner.
* Cependant :
** On ne veut pas valider le comportement du `UserRepository`.
** Pire, on ne veut pas se connecter à une base de donnée pendant un test unitaire.

== Remplacer le UserRepository (1/3)

Solution : On fournit une "fausse implémentation" au service.

[source,java]
--
// src/test/java/com/cicdlectures/demoapp/user/UserServiceTests.java

  private UserRepository repository;

  private UserService subject;

  @BeforeEach
  public void init() {
    this.repository = mock(UserRepository.class);
    this.subject = new UserService(this.repository);
  }
--

== Remplacer le UserRepository (2/3)

que l'on pilote dans les tests!

[source,java]
--
  @Test
  public void createsUser() {
    // Quand le repository reçoit l'appel findByName avec la valeur "foo"
    // Alors il retourne null.
    when(repository.findByName("foo")).thenReturn(null);
  }
--

== Remplacer le UserRepository (3/3)

et on valide les interactions avec cette instance!

[source,java]
--
  @Test
  public void createsUser() {
    User user = new User("foo", 10);
    // [...]
    // Verifie que l'instance de repository a reçu saveUser avec l'objet user.
    verify(this.repository).saveUser(user);
  }
--

== Résumé

[source,java]
--
  @Test
  @DisplayName("creates an user")
  public void createsUser() {
    User user = new User("foo", 10);
    when(repository.findByName("foo")).thenReturn(null);

    subject.createUser(user);

    verify(this.repository).saveUser(user);
  }
--

== A vous de jouer pour l'autre cas :)

[source,java]
--
  @Test
  @DisplayName("does not create a user if it already exists")
  public void doesNotcreateUserIfAlreadyExist() {
    fail("not implemented");
  }
--

[source, java]
--
  // Un peu d'aide :)

  // Retourne l'utilisateur passé en paramètre.
  when(repository.findByName("foo")).thenReturn(user);

  // Vérifie que la methode saveUser du repository n'est
  // jamais appelé avec l'instance user.
  verify(this.repository, never()).saveUser(user);
--

== Test Unitaire: Solution Exercice 2

[source, bash]
----
git checkout ut-exercise-2-solution
----

== Test Unitaire : Pro / Cons

* ✅ Super rapides (<1s) et légers a executer
* ✅ Pousse à avoir un bon design de code
* ✅ Efficaces pour tester des cas limites
* ❌ Peu réalistes

[%notitle]
== fail

video::ut-fail-1.mp4[width="600",options="autoplay,loop,nocontrols"]

[%notitle]
== fail2

video::ut-fail-2.mp4[width="600",options="autoplay,loop,nocontrols"]

== Test d'Integration

* Test validant qu'un assemblage d'unités se comportent comme prévu.
* Par exemple :
** Prouve que `GET /users` retourne la liste des utilisateurs en base

== Définition du Système à tester

image:applayers.svg[width="800"]

(omission volontaire d'une couche de service a des fins de simplification)

[.notes]
--
* On teste la chaine user <=> controller <=> repository
--

== HTTP Client

Emet une requiête HTTP et inteprète la réponse.

Par exemple: curl, Firefox, Chrome, une autre app.

== UserController

Implémentation d'une requête HTTP par une methode java.
[.small]
(en passant par un peu de magie spring)

* Parse les paramètres de la requête HTTP (headers, query parameters)
* Appelle la couche de données
* Réponds la donnée récupérée de la couche de données dans un format négocié.
** HTML, JSON, XML ...

== UserRepository

* Transforme un appel java en une requête à la base de données
** SQL, PL/SQL, CQL, JSON (MongoDB, Elastisearch...)
* Transforme la réponse de la base de donnée en objets java

== Base de données

* Reçoit des requêtes
* Réponds des données

Nous allons utiliser link:https://www.h2database.com[h2], une base de donnée SQL implémentée en java et s'executant en mémoire.

== En résumé

image:applayers.svg[width="800"]

== De quel point de vue testons nous ?

Du point de vue du client HTTP.

== Exercice

Implémentez la méthode `getUsers` de la classe `UserController` et sa suite de tests pour qu'elle respecte le contrat suivant:

* Si le paramètre de requête "name" est vide alors on retourne tous les utilisateurs connus
* Si le paramètre de requête "name" non-vide alors on retourne la liste des utilisateurs ayant ce nom.

== Base de données 2, le retour !

[source, java]
--
// src/main/java/com/cicdlectures/demoapp/user/UserRepository.java
import org.springframework.data.repository.CrudRepository;

public interface UserRepository extends CrudRepository<User,Long> {
    // CrudRepository fournit des metodes de bases pour accéder à la donnée
    //
    // Par exemple:
    //
    // public Iterable<User> findAll();

    public List<User> findByName(String name);

}
--

== Interpréter et répondre à une requête HTTP

[source, java]
--
@RestController
public class UserController {

  @Autowired
  private UserRepository users;

  @GetMapping(path="/users", produces = "application/json")
  public Iterable<User> getUsers(@RequestParam(value = "name",defaultValue = "") String name) {
    // Appelle le user repository pour récupérer les données.
  }

}
--

== Notre client: le test!

[source, java]
--
// src/test/java/com/cicdlectures/demoapp/user/UserControllerIT.java

// Crée et initialise le serveur et le lance sur un port aléatoire.
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
public class UserControllerTests {
  // [...]

  // Mets à jour l'attribut `url` avec le port du serveur (décidé aléatoirement).
  @BeforeEach
  public void setUp() throws Exception {
    this.url = new URL("http://localhost:" + port + "/users");
  }

  // Après chaque test, on vide la base de donnée.
  @AfterEach
  public void tearDown() throws Exception {
    this.userRepository.deleteAll();
  }
--

== !

[source, java]
--
  @Test
  @DisplayName("lists all users")
  public void testUsersList() throws Exception {
    // Définition du jeu de données.
    User[] wantUsers = {
      new User("John", 43),
      new User("Philip", 93),
      new User("Mitchell", 31)
    };

    // Enregistrement du jeu de données en base.
    for (User user : wantUsers) {
      this.userRepository.save(user);
    }

    // Appel HTTP GET /users sur l'URL du serveur lancé pour le test.
    ResponseEntity<User[]> response = this.template
      .getForEntity(url.toString(), User[].class);

    // Interprétation du corps de la réponse HTTP.
    User[] gotUsers = response.getBody();

    // Verifions que le corps de la réponse correspond bien à notre jeu de données.
    assertArrayEquals(wantUsers, gotUsers);
  }
--

== Implémentation du premier cas de test

[source, java]
--
public class UserController {

  @GetMapping(path="/users", produces = "application/json")
  public Iterable<User> getUsers(@RequestParam(value = "name",defaultValue = "") String name) {
    return this.users.findAll();
  }

}
--

== A vous de jouer pour le second cas !

[source,java]
--
  @Test
  @DisplayName("filters users by name")
  public void testUsersListFiltersByName() throws Exception {
    // Valide que lorsque le paramètre de requête name est non vide
    // Alors l'application réponds les utilisateurs portant ce nom.
  }
--

[source, java]
--
  // Un peu d'aide :)

  // Vérifier qu'une chaine de caractère est non vide
  if (!name.isBlank()) {
    // ...
  }

  // Requête avec le paramètre de requête name à la valeur "Philip"
  ResponseEntity<User[]> response = this.template
      .getForEntity(url.toString()+ "?name=Philip", User[].class);
--

[source, bash]
----
# Lancer les tests d'intégration
mvn verify
----

== Test d'Integration : Solution

[source,bash]
--
git checkout it-exercise-1-solution
--

== Test d'Integration : Pro / Cons

* ✅ Relativement réalistes
* ✅ Potentiellement complexes
* ✅ Feeback "rapide" 1s < t < 1m
* ❌ Moins flexibles

== Test de Bout en Bout

* Test validant qu'un cas d'utilisation est correctement implémenté par le logiciel
* Tests idéalement décrits de façon non technique
* Par exemple :
** En tant qu'un utilisateur authentifié
** Quand je remplis le formulaire correctement et appuie sur le bouton "OK"
** Alors un utilisateur est créé en base

== Demonstration

== Test de Bout en Bout : Pro / Cons

* ✅ Au plus proche d'un cas réel
* ✅ Teste tous les composants du logiciel
* ❌ Lents (~1m)
* ❌ Complexes
* ❌ Peu flexibles
