name: Slides Workflow

on:
  push:

jobs:
  build:
    name: 'Build Slides'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Build'
        run: make build
      - name: 'Verify'
        run: make verify
      - name: 'Upload dist/ as artefact'
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    # if: github.ref == 'refs/heads/master'
    steps:
    - name: 'Download dist/ Artefacts'
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: ./dist
    - name: 'DEBUG'
      run: pwd -P && find . -type f
    - name: 'Deploy'
      uses: netlify/actions/cli@6c34c3f
      with:
        args: deploy --dir=./dist
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
