name: Slides Workflow

on:
  push:

jobs:
  build:
    name: 'Build Slides'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Build'
        run: make build
      - name: 'Verify'
        run: make verify
      - name: 'PDF'
        run: make pdf
      - name: 'Upload dist/ as artefact'
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: 'Download dist/ Artefacts'
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: ./dist
    - name: 'Deploy'
      uses: netlify/actions/cli@master
      with:
        args: deploy --dir=./dist ${{ github.ref == 'refs/heads/master' && '--prod' || '' }}
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
