name: Slides Workflow

on:
  push:

jobs:
  build:
    name: 'Build Slides'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Build'
        run: make build
      - name: 'Verify'
        run: make verify
  deploy:
    runs-on: ubuntu-latest
    needs: build
    # if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@master
    - name: 'Deploy'
      uses: netlify/actions/cli@6c34c3f
      with:
        args: deploy --dir=./dist
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
