name: Slides Workflow

on:
  create:
    tags:
      - '*'
  push:
    branches-ignore:
      - gh_pages
    tags:
      - '*'
  workflow_dispatch:

env:
  ## Override default value for Docker cached image
  IMAGE_CACHE_NAME: "dduportal/slides:cicd-lectures"

jobs:
  build:
    name: 'Build Slides'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Login to DockerHub'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: 'Build'
        run: make build
      - name: PDF on main branch
        if: github.ref == 'refs/heads/2021'
        run: make pdf
      - name: 'Caching for later builds'
        if: github.ref == 'refs/heads/2021'
        run: docker push "${IMAGE_CACHE_NAME}"
      - name: 'Verify'
        run: make verify
      - name: 'Upload dist/ as artefact'
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: 'Download dist/ Artefacts'
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: ./dist
    - name: Get tag value
      if: startsWith(github.ref, 'refs/tags/')
      id: tags
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: 'Deploy Tag'
      if: startsWith(github.ref, 'refs/tags/')
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        destination_dir: ${{ steps.tags.outputs.tag }}
    - name: Get branch name
      if: startsWith(github.ref, 'refs/heads/')
      id: branches
      run: echo ::set-output name=branch::${GITHUB_REF#refs/heads/}
    - name: 'Deploy Main Branch'
      if: startsWith(github.ref, 'refs/heads/')
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        destination_dir: ${{ steps.branches.outputs.branch }}
