name: Slides Workflow

on:
  push:

env:
  ## Override default value for Docker cached image
  IMAGE_CACHE_NAME: "dduportal/slides:cicd-lectures"

jobs:
  build:
    name: 'Build Slides'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Login to DockerHub'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: 'Build'
        run: make build
      - name: 'Caching for later builds'
        if: github.ref == 'refs/heads/main'
        run: docker push "${IMAGE_CACHE_NAME}"
      - name: 'Verify'
        run: make verify
      - name: 'PDF'
        run: make pdf
      - name: 'Upload dist/ as artefact'
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: 'Download dist/ Artefacts'
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: ./dist
    - name: 'Deploy'
      uses: netlify/actions/cli@master
      with:
        args: deploy --dir=./dist ${{ github.ref == 'refs/heads/master' && '--prod' || '' }}
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
