name: Slides Workflow

on:
  create:
    tags:
      - '*'
  push:
    branches-ignore:
      - gh_pages
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

env:
  ## Override default value for Docker cached image
  IMAGE_CACHE_NAME: "ghcr.io/${{ github.repository_owner }}/slides:cicd-lectures"
  PRINCIPAL_BRANCH: "2023"

jobs:
  build-slides:
    name: 'Build Slides'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Build'
        run: make build
      - name: 'Caching for later builds'
        if: github.event_name == 'push' && github.event_name != 'pull_request'
        run: docker push "${IMAGE_CACHE_NAME}"
      - name: 'Verify'
        run: make verify
      - name: 'Upload dist/ as artefact'
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

  build-pdf:
    name: 'Build PDF'
    runs-on: ubuntu-latest
    # Only generate PDF when pushing code on a branch of the repository
    if: github.event_name == 'push'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Build'
        run: make build
      - name: PDF on main branch
        if: github.ref == 'refs/heads/${{ env.PRINCIPAL_BRANCH }}'
        run: make pdf
      - name: 'Upload dist/slides.pdf as artefact'
        uses: actions/upload-artifact@v2
        with:
          name: pdf
          path: dist/slides.pdf

  deploy:
    runs-on: ubuntu-latest
    needs: [build-slides,build-pdf]
    # Only run deploy when pushing code on a branch of the repository
    if: github.event_name == 'push'
    steps:
    - name: 'Download dist/ Artefacts'
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: ./dist
    - name: 'Download dist/slides.pdf artefact'
      uses: actions/download-artifact@v2
      with:
        name: pdf
        path: ./dist
    - name: Get tag value
      if: startsWith(github.ref, 'refs/tags/')
      id: tags
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: 'Deploy Tag'
      if: startsWith(github.ref, 'refs/tags/')
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        destination_dir: ${{ steps.tags.outputs.tag }}
    - name: Get branch name
      if: startsWith(github.ref, 'refs/heads/')
      id: branches
      run: echo ::set-output name=branch::${GITHUB_REF#refs/heads/}
    - name: 'Deploy Main Branch'
      if: startsWith(github.ref, 'refs/heads/')
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        destination_dir: ${{ steps.branches.outputs.branch }}
