name: Slides Workflow

on:
  push:

jobs:
  build:
    name: 'Build Slides'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Build'
        run: make build
